# Generated by Django 2.2.9 on 2020-01-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('related_link', models.CharField(max_length=200)),
                ('posted_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
