# Generated by Django 2.2.9 on 2020-01-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='related_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
