# Generated by Django 2.2.9 on 2020-01-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20200126_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='related_link',
            new_name='related_link_name',
        ),
    ]
